name: Build gemc

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-fedora36

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2.0.0
      - name: Build gemc
        run: |
          ./ci/build_gemc.sh
      - name: Copy gemc binary
        uses: actions/upload-artifact@v4
        with:
          name: gemc
          path: /cvmfs/oasis.opensciencegrid.org/jlab/geant4/gemc

