name: Detector Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
#    container: jeffersonlab/cvmfs:fedora36
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 4.4.2
#          - 5.1
#          - 5.2
#          - 5.3
        detector:
          - targets
#          - dc
    steps:
      - uses: cvmfs-contrib/github-action-cvmfs@v3.1
      - name: ${{ matrix.tag }} ${{ matrix.detector }} test
        run: |
          ./ci/detectors_test.sh -t ${{ matrix.tag }} -d ${{ matrix.detector }}