name: Detector Tests

 # Triggers the workflow on all pushes to main and all pull requests
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - targets
          - dc
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ${{ matrix.detector }} test
        run: |
          ./ci/detectors_test.sh -d ${{ matrix.detector }}


