name: Detector Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: jeffersonlab/cvmfs:fedora36
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 5.4
        detector:
          - targets
#          - dc
    steps:
#      - uses: cvmfs-contrib/github-action-cvmfs@v3.1
      - name: Checkout
        uses: actions/checkout@main
      - name: Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1.8.0
      - name: ${{ matrix.tag }} ${{ matrix.detector }} test
        run: |
          ./ci/detectors_test.sh -t ${{ matrix.tag }} -d ${{ matrix.detector }}
      - uses: gitboard-io/gitboard-action@main
        with:
          username: maureeungaro
          key: 3d8e9059-a164-4bea-9541-1cb8789d805b

