name: Detector Tests
permissions:
  contents: read
  pull-requests: write
  security-events: write

 # Triggers the workflow on all pushes to main and all pull requests
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detectors-test:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - targets
          - dc
        language: [ 'c-cpp' ]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: ${{ matrix.detector }} test
        run: |
          ./ci/detectors_test.sh -d ${{ matrix.detector }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          # Generate category based on matrix values for better organization of results
          category: "/language:${{matrix.language}}/detector:${{matrix.detector}}"

  detectors-test-final:
    needs:
      - detectors-test
    runs-on: ubuntu-latest
    steps:
      - name: fail
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: pass
        run: |
          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
          exit 0
