# https://github.com/pyTooling/Actions/tree/main/releaser
name: 'dev release'

on:
  schedule:
    # every day at 1:25 and 13:25 - UTC time zone
    - cron: '44 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dev-release:
    runs-on: ubuntu-latest
    steps:

    # Clone repository
    - uses: actions/checkout@v3

    # Update tag and pre-release
    # - Update (force-push) tag to the commit that is used in the workflow.
    # - Upload artifacts defined by the user.
    - uses: pyTooling/Actions/releaser@r0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          config/*
          source/*
          experiments/*