name: Experiments Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
    branches:
      - '*'
  # Trigger on any PR
  pull_request:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-fedora36
    outputs:
      matrix:  ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Creates list of gcards
        uses: actions/checkout@main
      - id: set-matrix
        run: |
          export JSON=$( ./ci/gcards_to_test.sh )
          echo generate-matrix: $JSON
          echo "matrix=$( echo "$JSON" | tr -d '\n' )" >> $GITHUB_OUTPUT
  

  dev-gcards-test:
    name: ${{ matrix.detector }}
    needs: generate-matrix
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ${{ matrix.detector }} tests
        run: |
          ./ci/experiments_test.sh -g ${{ matrix.gcard }}



