name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  comparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec
          - pcal
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run ${{ matrix.detector }} comparison
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.detector }}
          path: /root/logs

    # Output the list of detectors for the summary job
    outputs:
      detectors: ${{ toJson(matrix.detector) }}


  summary:
    needs: comparison
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        run: |
          # Get the detectors output from the comparison job
          detectors="${{ needs.comparison.outputs.detectors }}"
          
          # Convert the string into an array
          IFS=',' read -r -a detector_array <<< "${detectors}"
          
          # Create a directory to store all downloaded logs
          mkdir -p aggregated_logs

          # Loop through detectors and download each artifact dynamically
          for detector in "${detector_array[@]}"; do
            echo "Downloading logs for detector: $detector"
            # Use the 'uses' keyword to correctly call the action
            - uses: actions/download-artifact@v3
              with:
                name: "logs-$detector"
                path: "aggregated_logs/$detector"
          done
          
      - name: Aggregate Logs and Generate Table
        run: |
          # Aggregate all logs into a single file
          cat aggregated_logs/*/*.log > comparison.log

          # Generate the table header
          table="
          | Detector | Variation | Run | Status  |
          |----------|-----------|-----|---------|
          "

          # Read the aggregated log and append rows to the table
          while IFS=: read -r detector variation run status; do
            table+="| $detector | $variation | $run | $status |\n"
          done < comparison.log

          # Write the table to the GitHub Actions summary
          echo -e "$table" >> $GITHUB_STEP_SUMMARY


      - name: Display Summary in Logs
        run: cat $GITHUB_STEP_SUMMARY