name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Notary:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Notary
        run: |
          ./ci/report_runs_and_variations.sh  > Summary.md
          cat Summary.md >> $GITHUB_STEP_SUMMARY

  Geometry:
    needs: Notary
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec
          - pcal
          - dc
          - ftof
          - ctof
          - cnd
          - bst
          - htcc
          - micromegas
          - ltcc
          - rich

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Geometry ${{ matrix.detector }} Comparison
        run: |
          ./ci/geometry_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: geologs-${{ matrix.detector }}
          path: /root/logs/

  Run:
    needs: Notary
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          #          - ec
          #          - pcal
          - dc
            #          - ftof
            #          - ctof
            #          - cnd
            #          - bst
            #          - htcc
            - micromegas
          # - ltcc
          - rich
          - ft
        # obtained with awk -F'value="' '/DIGITIZATION_VARIATION/ {split($2, a, "\""); print a[1]}' /opt/projects/clas12-config/gemc/dev/*  | sort -u
        variation:
          - default
          #          - rga_spring2018_mc
          - rga_fall2018_mc
          #          - rga_spring2019_mc
          - rgb_fall2019_mc
          #          - rgb_spring2019_mc
          #          - rgc_summer2022_mc
          - rgf_spring2020_mc
          - rgm_fall2021_mc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build GEMC
        run: |
          ./ci/build_gemc.sh
      - name: Install Software
        run: |
          ./ci/install_comparison_software.sh
      - name: GEMC ${{ matrix.detector }} Comparison
        run: |
          ./ci/gemc_comparison.sh -d ${{ matrix.detector }} -v ${{ matrix.variation }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: gemclogs-${{ matrix.detector }}-${{ matrix.variation }}
          path: /root/logs/

  GeoResults:
    needs: Geometry
    runs-on: ubuntu-latest
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: geologs-*
      - name: Generate Table
        run: |
          ls */*geo_comparison.log
          cat */*geo_comparison.log > comparison.log
          echo "| Detector | Geometry Variation | Run | Status  |" > Summary.md
          echo "|----------|--------------------|-----|---------|" >> Summary.md
          while IFS=: read -r detector variation run pass; do
            echo "| $detector | $variation | $run | $pass |" >> Summary.md
          done < comparison.log
          cat Summary.md >> $GITHUB_STEP_SUMMARY

  DigiResults:
    needs: Run
    runs-on: ubuntu-latest
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: gemclogs-*
      - name: Detailed Table
        run: |
          ls */*output_details.log
          cat */*output_details.log > comparison.log
          echo "| Detector | Geometry Variation | Run | Bank | Digitization Variations | Status  |" > Summary.md
          echo "|----------|--------------------|-----|------|-------------------------|---------|" >> Summary.md
          while IFS=: read -r detector variation run bank dvariations  pass; do
            echo "| $detector | $variation | $run | $bank | $dvariations | $pass |" >> Summary.md
          done < comparison.log
          cat Summary.md >> $GITHUB_STEP_SUMMARY
      - name: Summary Digitization Table
        run: |
          ls */*output_summary.log
          cat */*output_summary.log > comparison.log
          echo "| Detector | Digitization Variations | Status  |" > Summary.md
          echo "|----------|-------------------------|---------|" >> Summary.md
          while IFS=: read -r detector dvariations  pass; do
            echo "| $detector | $dvariations | $pass |" >> Summary.md
          done < comparison.log
          cat Summary.md >> $GITHUB_STEP_SUMMARY
      - name: Summary Detector Table
        run: |
          ls */*output_summary.log
          detectors=$( cat */*_output_summary.log | awk -F: '{print $1}' | sort -u)
          echo "| Detector | Status  |" > Summary.md
          echo "|----------|---------|" >> Summary.md
          for detector in $detectors; do
            if grep $detector | grep -q "❌" */*output_summary.log; then
                echo "| $detector | ❌ |" >> Summary.md
            elif grep $detector | grep -q "✅" */*output_summary.log; then
                echo "| $detector | ✅ |" >> Summary.md
            fi
          done
          cat Summary.md >> $GITHUB_STEP_SUMMARY