name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  comparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run ${{ matrix.detector }} comparison
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.detector }}
          path: /root/logs/


  summary:
    needs: comparison
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact Names from Matrix
        run: |
          # Create a space-separated list of detectors from the matrix
          detectors="${{ needs.comparison.outputs.matrix | join(' ') }}"
          echo "Detectors from matrix: $detectors"
          echo "DETECTORS=$detectors" >> $GITHUB_ENV

      - name: Verify DETECTORS Variable
        run: echo "DETECTORS=$DETECTORS"
        env:
          DETECTORS: ${{ env.DETECTORS }}