name: Detector Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ${{ matrix.detector }} test
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}


