name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GeoComparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec
          - pcal
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Geometry ${{ matrix.detector }} Comparison
        run: |
          ./ci/geometry_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: geologs-${{ matrix.detector }}
          path: /root/logs/

  OutputComparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec
          - pcal
          - dc
          - ftof
          - htcc
        variation:
          - default
          - rga_spring2018_mc
          - rga_fall2018_mc
#          - rga_spring2019_mc
#          - rgb_fall2019_mc
#          - rgb_spring2019_mc
#          - rgc_summer2022_mc
#          - rgf_spring2020_mc
#          - rgm_fall2021_mc


    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: GEMC ${{ matrix.detector }} Comparison
        run: |
          ./ci/gemc_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: gemclogs-${{ matrix.detector }}
          path: /root/logs/

  Geometry:
    needs: GeoComparison
    runs-on: ubuntu-latest
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: geologs-*
      - name: Generate Table
        run: |
         ls */*geo_comparison.log
         cat */*geo_comparison.log > comparison.log
         echo "| Detector | Geometry Variation | Run | Status  |" > Summary.md
         echo "|----------|--------------------|-----|---------|" >> Summary.md
         while IFS=: read -r detector variation run pass; do
           echo "| $detector | $variation | $run | $pass |" >> Summary.md
         done < comparison.log
         cat Summary.md >> $GITHUB_STEP_SUMMARY

  Digitization:
    needs: OutputComparison
    runs-on: ubuntu-latest
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: gemclogs-*
      - name: Generate Table
        run: |
         ls */*output_comparison.log
         cat */*output_comparison.log > comparison.log
         echo "| Detector | Geometry Variation | Run | Digitization Variations | Status  |" > Summary.md
         echo "|----------|--------------------|-----|-------------------------|---------|" >> Summary.md
         while IFS=: read -r detector variation dvariations run pass; do
           echo "| $detector | $variation | $run | $pass |" >> Summary.md
         done < comparison.log
         cat Summary.md >> $GITHUB_STEP_SUMMARY
