name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Comparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run ${{ matrix.detector }} comparison
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.detector }}
          path: /root/logs/


  Geometry:
    needs: Comparison
    runs-on: ubuntu-latest
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: logs-*
      - name: Generate Table
        run: |
         ls */*geo_comparison.log
         cat */*geo_comparison.log > geo_comparison.log
         echo "| Detector | Variation | Run | Status  |" > Summary.md
         echo "|----------|-----------|-----|---------|" >> Summary.md
         while IFS=: read -r detector variation run pass; do
           echo "| $detector | $variation | $run | $pass |" >> Summary.md
         done < geo_comparison.log
         cat Summary.md >> $GITHUB_STEP_SUMMARY
