name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  comparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ec
          - pcal
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ${{ matrix.detector }} comparison
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}
          if [ ! -f comparison.log ]; then
            echo "" > comparison.log
          fi
          cat /root/${{ matrix.detector }}_comparison.log >> comparison.log
      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: comparison-log
          path: comparison.log

  summary:
    needs: comparison
    runs-on: ubuntu-latest
    steps:
      - name: Download log
        uses: actions/download-artifact@v3
        with:
          name: comparison-log

      - name: Generate Summary Table
        run: |
          # Generate the table header
          table="
          | System | Variation | Run | Status  |
          |----------|-----------|-----|---------|
          "

          # Read the log file and append rows to the table
          while IFS=: read -r detector variation run status; do
            table+="| $detector | $variation | $run | $status |\n"
          done < comparison.log

          # Write the table to the GitHub Actions summary
          echo -e "$table" >> $GITHUB_STEP_SUMMARY

      - name: Display Summary in Logs
        run: cat $GITHUB_STEP_SUMMARY