name: TEXT vs SQLITE

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  comparison:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix:
        detector:
          - dc
          - ftof
          - htcc

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run ${{ matrix.detector }} comparison
        run: |
          ./ci/variation_run_comparison.sh -d ${{ matrix.detector }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.detector }}
          path: /root/logs

    # Output the list of detectors for the summary job
    outputs:
      detectors: ${{ toJson(matrix) }}


  summary:
    needs: comparison
    runs-on: ubuntu-latest
    strategy:
      matrix:
        detector:
          - dc
          - ftof
          - htcc
    steps:
      - name: Download ${{ matrix.detector }} artifact
        uses: actions/download-artifact@v4
        with:
          name: logs-${{ matrix.detector }}
          path: /root/logs/logs-${{ matrix.detector }}


      - name: Aggregate Logs and Generate Table
        run: |
          # Aggregate all logs into a single file
          cat /root/logs/*.log > comparison.log

          # Generate the table header
          table="
          | Detector | Variation | Run | Status  |
          |----------|-----------|-----|---------|
          "

          # Read the aggregated log and append rows to the table
          while IFS=: read -r detector variation run status; do
            table+="| $detector | $variation | $run | $status |\n"
          done < comparison.log

          # Write the table to the GitHub Actions summary
          echo -e "$table" >> $GITHUB_STEP_SUMMARY


      - name: Display Summary in Logs
        run: cat $GITHUB_STEP_SUMMARY